### ISSUE TITLE
Retrieve vector values using cartesian coordinates

### ISSUE THREAD

**Issue by stefnotch** [akira-cn/babel-plugin-transform-gl-matrix#1]
It would be great to be able to access vector values with `.x`, `.y`, `.z` instead of `[0]`, `[1]`, `[2]`

e.g.
```javascript
const v = vec3(1, 0, 0);
const xValue = v.x;
```

**Comment by stefnotch** [comment]
Relevant issue: https://github.com/toji/gl-matrix/issues/276

**Comment by akira-cn** [comment]
Now supports xyzw, rgba, stpq, the same as glsl!
